In [1]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
np.__version__

'1.21.6'

In [5]:
dat = np.arange(10).reshape(5, 2)
dat

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
mat = np.array([0,1,1,0]).reshape(2, 2)
mat

array([[0, 1],
       [1, 0]])

In [13]:
win = sliding_window_view(dat, (mat.shape))
print(win.shape)
print(win)

(4, 1, 2, 2)
[[[[0 1]
   [2 3]]]


 [[[2 3]
   [4 5]]]


 [[[4 5]
   [6 7]]]


 [[[6 7]
   [8 9]]]]


In [15]:
res = win * mat
print(res.shape)
print(res)

(4, 1, 2, 2)
[[[[0 1]
   [2 0]]]


 [[[0 3]
   [4 0]]]


 [[[0 5]
   [6 0]]]


 [[[0 7]
   [8 0]]]]


In [17]:
(win * mat).sum(axis=-1).sum(axis=-1)

array([[ 3],
       [ 7],
       [11],
       [15]])