In [6]:
import numpy as np
from sklearn import preprocessing

In [3]:
seq = "TTCTCATTGGT"

In [7]:
seq_str = "TTCTCATTGGT"
seq_arr = np.array(list(seq_str))
print(seq_arr)

['T' 'T' 'C' 'T' 'C' 'A' 'T' 'T' 'G' 'G' 'T']


https://2-bitbio.com/2018/06/one-hot-encode-dna-sequence-using.html

## Label Encoder

In [10]:
le = preprocessing.LabelEncoder()
le = le.fit(["A", "T", "C", "G"])
le.classes_

array(['A', 'C', 'G', 'T'], dtype='<U1')

In [11]:
le.transform(seq_arr)

array([3, 3, 1, 3, 1, 0, 3, 3, 2, 2, 3])

In [13]:
le.classes_ = np.array(["A", "T", "C", "G"])
le.transform(seq_arr)

array([1, 1, 2, 1, 2, 0, 1, 1, 3, 3, 1])

In [22]:
le.classes_ = np.array(["T", "A", "C", "G"])
le.transform(seq_arr)

array([0, 0, 2, 0, 2, 1, 0, 0, 3, 3, 0])

In [23]:
le.classes_ = np.array(["T", "A", "C", "G"])
seq_int = le.transform(seq_arr)

## One Hot Encoder

In [24]:
arr = seq_int.reshape(-1, 1)
arr

array([[0],
       [0],
       [2],
       [0],
       [2],
       [1],
       [0],
       [0],
       [3],
       [3],
       [0]])

In [25]:
enc = preprocessing.OneHotEncoder(sparse=False)
enc.fit_transform(arr)

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])